name: pokedex
description: Pokemon application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  json_annotation: ^4.6.0
  dio: ^5.0.3
  auto_size_text: ^3.0.0
  freezed_annotation: ^2.1.0
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.2.1
  palette_generator: ^0.3.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  go_router: ^4.2.0
  path_provider: ^2.0.11
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  bloc_test: ^9.0.3
  http_mock_adapter: ^0.4.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  flutter_gen_runner: ^5.2.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
